"""Lead management - Tracks revenue generated by AI agents"""

from fastapi import APIRouter, Query
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime

router = APIRouter()

class LeadCreate(BaseModel):
    email: str
    company: str
    agent_id: int
    metadata: Optional[dict] = {}

@router.post("/")
async def create_lead(lead: LeadCreate):
    """Track lead generated by AI agent - feeds revenue attribution"""
    return {
        "id": 1,
        "email": lead.email,
        "company": lead.company,
        "status": "new",
        "estimated_value": 2500,
        "created_at": datetime.utcnow().isoformat(),
        "message": "Lead tracked. Revenue attribution active."
    }

@router.get("/")
async def list_leads(
    agent_id: Optional[int] = None,
    status: Optional[str] = None,
    limit: int = Query(50, le=100)
):
    """List leads with revenue metrics"""
    return {
        "leads": [],
        "summary": {
            "total_leads": 0,
            "pipeline_value": 0,
            "conversion_rate": 0.28,
            "avg_deal_size": 12500
        }
    }

@router.get("/revenue-metrics")
async def get_revenue_metrics():
    """Key metrics for $200K target - used in dashboard"""
    return {
        "leads_this_period": 0,
        "qualified_meetings": 0,
        "pipeline_generated": 0,
        "revenue_attributed": 0,
        "target_14_day": 200000,
        "progress_pct": 0,
        "benchmarks": {
            "emails_per_lead": 150,
            "lead_to_meeting": 0.15,
            "meeting_to_close": 0.25,
            "avg_deal": 12500
        }
    }
