#!/bin/bash
set -e

echo "========================================="
echo "  AgentForge AI - Stripe Setup Guide"
echo "========================================="
echo ""
echo "Follow these steps to configure Stripe billing:"
echo ""
echo "1. Go to https://dashboard.stripe.com"
echo "2. Create three Products with these prices:"
echo ""
echo "   Product: AgentForge Starter"
echo "   Price: \$499.00/month (recurring)"
echo "   -> Copy the price ID (price_xxx) to STRIPE_PRICE_STARTER"
echo ""
echo "   Product: AgentForge Growth"
echo "   Price: \$1,499.00/month (recurring)"
echo "   -> Copy the price ID (price_xxx) to STRIPE_PRICE_GROWTH"
echo ""
echo "   Product: AgentForge Enterprise"
echo "   Price: \$4,999.00/month (recurring)"
echo "   -> Copy the price ID (price_xxx) to STRIPE_PRICE_ENTERPRISE"
echo ""
echo "3. Get your API keys from Developers > API Keys:"
echo "   -> Secret key (sk_live_xxx) -> STRIPE_SECRET_KEY"
echo "   -> Publishable key (pk_live_xxx) -> NEXT_PUBLIC_STRIPE_KEY"
echo ""
echo "4. Set up webhook at Developers > Webhooks:"
echo "   URL: https://your-domain.com/api/v1/billing/webhook"
echo "   Events: checkout.session.completed, customer.subscription.updated,"
echo "           customer.subscription.deleted, invoice.paid"
echo "   -> Webhook signing secret (whsec_xxx) -> STRIPE_WEBHOOK_SECRET"
echo ""
echo "5. Update your .env files and restart:"
echo "   docker compose restart backend"
echo ""
